export type LeaveFormField =
  | {
      name: string;
      type: 'checkbox';
      page: number;
      x: number;
      y: number;
      width: number;
      height: number;
      marginHeight: number;
      marginWidth: number;
    }
  | {
      name: string;
      type: 'text' | 'textarea';
      page: number;
      x: number;
      y: number;
      width: number;
      height: number;
      marginHeight: number;
      marginWidth: number;
      fontSize: number;
    };

export const PDF_A4_WIDTH = 595;
export const PDF_A4_HEIGHT = 842;

// Section 1-5: Office, Name, Date, Position, Salary
export const headerFields: LeaveFormField[] = [
  {
    name: 'officeDepartment',
    type: 'text',
    page: 1,
    x: 40,
    y: 708,
    width: 165,
    height: 14,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'nameLast',
    type: 'text',
    page: 1,
    x: 220,
    y: 708,
    width: 100,
    height: 14,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'nameFirst',
    type: 'text',
    page: 1,
    x: 326,
    y: 708,
    width: 100,
    height: 14,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'nameMiddle',
    type: 'text',
    page: 1,
    x: 430,
    y: 708,
    width: 100,
    height: 14,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'dateOfFiling',
    type: 'text',
    page: 1,
    x: 118,
    y: 682,
    width: 70,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'position',
    type: 'text',
    page: 1,
    x: 270,
    y: 682,
    width: 130,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'salary',
    type: 'text',
    page: 1,
    x: 455,
    y: 682,
    width: 78,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
];

// Section 6A: Type of Leave checkboxes (left column)
export const leaveTypeFields: LeaveFormField[] = [
  {
    name: 'vacationLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 624,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'mandatoryForcedLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 609,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'sickLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 595,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'maternityLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 580,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'paternityLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 565,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'specialPrivilegeLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 552,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'soloParentLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 537,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'studyLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 522,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'vawcLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 509,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'rehabilitationPrivilege',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 495,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'specialLeaveBenefitsWomen',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 480,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'specialEmergencyLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 465,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'adoptionLeave',
    type: 'checkbox',
    page: 1,
    x: 46,
    y: 450,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'othersLeaveType',
    type: 'text',
    page: 1,
    x: 45,
    y: 410,
    width: 170,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
];

// Section 6B: Details of Leave (right column)
export const leaveDetailsFields: LeaveFormField[] = [
  // In case of Vacation/Special Privilege Leave
  {
    name: 'withinPhilippinesCheckbox',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 609,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'withinPhilippinesText',
    type: 'text',
    page: 1,
    x: 410,
    y: 610,
    width: 120,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'abroadCheckbox',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 595,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'abroadText',
    type: 'text',
    page: 1,
    x: 395,
    y: 598,
    width: 130,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  // In case of Sick Leave
  {
    name: 'inHospitalCheckbox',
    type: 'checkbox',
    page: 1,
    x: 321,
    y: 565,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'inHospitalText',
    type: 'text',
    page: 1,
    x: 430,
    y: 567,
    width: 95,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'outPatientCheckbox',
    type: 'checkbox',
    page: 1,
    x: 321,
    y: 552,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'outPatientText',
    type: 'text',
    page: 1,
    x: 435,
    y: 553,
    width: 90,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'illnessExtraLine',
    type: 'text',
    page: 1,
    x: 320,
    y: 540,
    width: 200,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  // In case of Special Leave Benefits for Women
  {
    name: 'specifyIllnessWomen',
    type: 'text',
    page: 1,
    x: 380,
    y: 510,
    width: 140,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'specifyIllnessWomenLine2',
    type: 'text',
    page: 1,
    x: 320,
    y: 498,
    width: 200,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  // In case of Study Leave
  {
    name: 'completionMastersDegree',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 465,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'barBoardExamReview',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 450,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  // Other purpose
  {
    name: 'monetizationLeaveCredits',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 422,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'terminalLeave',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 408,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
];

// Section 6C: Number of working days and inclusive dates
export const workingDaysFields: LeaveFormField[] = [
  {
    name: 'numberOfWorkingDays',
    type: 'text',
    page: 1,
    x: 54,
    y: 378,
    width: 180,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'inclusiveDates',
    type: 'text',
    page: 1,
    x: 54,
    y: 350,
    width: 180,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
];

// Section 6D: Commutation
export const commutationFields: LeaveFormField[] = [
  {
    name: 'notRequested',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 375,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'requested',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 360,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
];

// Section 7A: Certification of Leave Credits
export const leaveCertificationFields: LeaveFormField[] = [
  {
    name: 'asOf',
    type: 'text',
    page: 1,
    x: 126,
    y: 288,
    width: 100,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'totalEarnedVL',
    type: 'text',
    page: 1,
    x: 135,
    y: 260,
    width: 75,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'totalEarnedSL',
    type: 'text',
    page: 1,
    x: 212,
    y: 260,
    width: 73,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'lessApplicationVL',
    type: 'text',
    page: 1,
    x: 135,
    y: 250,
    width: 73,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'lessApplicationSL',
    type: 'text',
    page: 1,
    x: 212,
    y: 250,
    width: 73,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'balanceVL',
    type: 'text',
    page: 1,
    x: 135,
    y: 240,
    width: 73,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'balanceSL',
    type: 'text',
    page: 1,
    x: 212,
    y: 240,
    width: 73,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
];

// Section 7B: Recommendation
export const recommendationFields: LeaveFormField[] = [
  {
    name: 'forApproval',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 285,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'forDisapproval',
    type: 'checkbox',
    page: 1,
    x: 320,
    y: 270,
    width: 8,
    height: 8,
    marginHeight: 0,
    marginWidth: 0,
  },
  {
    name: 'disapprovalReasonText',
    type: 'text',
    page: 1,
    x: 415,
    y: 275,
    width: 105,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'disapprovalReasonLine2',
    type: 'text',
    page: 1,
    x: 332,
    y: 261,
    width: 190,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'disapprovalReasonLine3',
    type: 'text',
    page: 1,
    x: 332,
    y: 250,
    width: 190,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'disapprovalReasonLine4',
    type: 'text',
    page: 1,
    x: 332,
    y: 240,
    width: 190,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
];

// Section 7C: Approved for
export const approvedForFields: LeaveFormField[] = [
  {
    name: 'daysWithPay',
    type: 'text',
    page: 1,
    x: 58,
    y: 172,
    width: 30,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'daysWithoutPay',
    type: 'text',
    page: 1,
    x: 58,
    y: 163,
    width: 30,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'othersSpecify',
    type: 'text',
    page: 1,
    x: 58,
    y: 150,
    width: 30,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
];

// Section 7D: Disapproved due to
export const disapprovedDueToFields: LeaveFormField[] = [
  {
    name: 'disapprovedLine1',
    type: 'text',
    page: 1,
    x: 332,
    y: 162,
    width: 190,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  {
    name: 'disapprovedLine2',
    type: 'text',
    page: 1,
    x: 332,
    y: 150,
    width: 190,
    height: 10,
    marginHeight: 0,
    marginWidth: 0,
    fontSize: 0.6,
  },
  // {
  //   name: 'municipalMayor',
  //   type: 'text',
  //   page: 1,
  //   x: 210,
  //   y: 105,
  //   width: 150,
  //   height: 10,
  //   marginHeight: 0,
  //   marginWidth: 0,
  //   fontSize: 0.6,
  // },
];

export const allLeaveFormFields: LeaveFormField[] = [
  ...headerFields,
  ...leaveTypeFields,
  ...leaveDetailsFields,
  ...workingDaysFields,
  ...commutationFields,
  ...leaveCertificationFields,
  ...recommendationFields,
  ...approvedForFields,
  ...disapprovedDueToFields,
];
